### ISSUE TITLE
Python releases post DataFusion 7.0.0 release

### ISSUE THREAD

**Issue by Jimexist** [datafusion-contrib/datafusion-python#31]
Hi @alamb and @jorgecarleitao 

I think we can probably publish a new version now. Any suggestions on how it'll be done?

**Comment by alamb** [comment]
Hi @Jimexist  -- I don't have any specific suggestions  but would be willing to help / assist with this process (as I am also somewhat interested in learning more about how the python integration and binding process works)

I think @houqp  did the release last time https://pypi.org/project/datafusion/. 

The maintainers are (I can invite you if you send me your username): 

![Screen Shot 2022-02-28 at 1 27 06 PM](https://user-images.githubusercontent.com/490673/156037738-a9d49b25-9ec3-4824-979c-8cebb56c58e3.png)

I removed some release instructions from datafusion here:  https://github.com/apache/arrow-datafusion/pull/1856/files but  perhaps we can revive the content in this repo?

**Comment by Jimexist** [comment]
Thanks for the info @alamb, my pypi account is https://pypi.org/user/etareduce/

@houqp any suggestions on creating a new release?

**Comment by houqp** [comment]
In the short run, we could just follow the instructions in the PR that was mentioned by @alamb . All we have to do is to push a git tag, then upload the wheel artifacts manually. The artifacts are built using github action, but we might need to adjust the tag pattern for this repo at https://github.com/datafusion-contrib/datafusion-python/blob/368b50ed9662d5e93c70b539f94cceace685265e/.github/workflows/build.yml#L22. I don't think we need to create rc releases anymore unless someone feels strongly about this.

If you are interested in improving the process, I would recommend uncomment the automated release job at https://github.com/datafusion-contrib/datafusion-python/blob/368b50ed9662d5e93c70b539f94cceace685265e/.github/workflows/build.yml#L116. The apache way disallows automated release, but we don't have this restriction in the contrib repo anymore ;)

**Comment by alamb** [comment]
> Thanks for the info @alamb, my pypi account is https://pypi.org/user/etareduce/

I sent an invite

**Comment by Jimexist** [comment]
see #43
