### ISSUE TITLE
Exception: DataFusion error: Plan("Invalid function 'mean'")

### ISSUE THREAD

**Issue by MrPowers** [datafusion-contrib/datafusion-python#56]
Here's the code I'm trying to run:

```python
import datafusion

ctx = datafusion.SessionContext()

ctx.register_csv("x", path)

ctx.sql("select id3, sum(v1) as v1, mean(v3) as v3 from x group by id3").collect()
```

It's giving me the following error:     return ctx.sql("select id3, sum(v1) as v1, mean(v3) as v3 from x group by id3").collect()
Exception: DataFusion error: Plan("Invalid function 'mean'")

Other queries like this one are running without issue:

```python
ctx.sql("select id1, sum(v1) as v1 from x group by id1").collect()
```

I am using DataFusion v0.6.0.

Am I missing an import?  Or are these functions not defined with the Python bindings yet?  Looks like this query is running fine with the Rust version, see [this PR](https://github.com/apache/arrow-datafusion/pull/2881/files) by @andygrove.  Thanks for the help!

**Comment by andygrove** [comment]
We have `avg` but not `mean`

**Comment by MrPowers** [comment]
Yep, that works, thanks 😄

**Comment by andygrove** [comment]
Here's a PR to upgrade the Python bindings to use DataFusion 10.0.0

https://github.com/datafusion-contrib/datafusion-python/pull/57
